### PR TITLE
Stage 1 1 markup - Live Demo Link

### PR DESCRIPTION
**Pull request by RandyPol**
I have created a new pull request to merge the Stage 1 1 markup branch code into the main branch. Additionally, to test the app without the need to create a new .env file or secret keys, I have deployed the Stage 1 1 markup branch on Vercel, which contains the secret API codes.

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for sending your project for review, it looks very good! I left several comments below so you can fix them and get more points on the next iteration. Good luck!✨

# Summary:
### Performance Criteria

#### Markup and JSX
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the `overflow: hidden` declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Nav menu is not displayed on 320 viewport
- [x]  Elements specified in the UI toolkit are used correctly (e.g. buttons, forms, text elements, etc).
- [ ]  Classes are named according to BEM specifications.
    * BEM is not applied correctly on the page - you use only blocks and modifiers entities without any connection between. Even with new technologies you still need correct final BEM class naming for better methodology scaling and supporting even big projects
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [ ]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
      * You should add fonts locally and import them using `@font-face` css rule
- [x]  There are no linting errors or warnings.

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
      * Not all requirements are met
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`
- [x]  No third-party JavaScript libraries are used unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [ ]  API requests are described inside the `App` component.
    * There's no App component
- [x]  There is no memory leak when hanging handlers. All handlers added with addEventListener are removed when the component is unmounted.
- [x]  API error handling:
  - [x] The user receives a message in case of an error.
      * Loading posts failed at the start of the page if I didn't login, but there's only infinite loading instead of error message
- [x]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
- [x]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed by clicking on the cross button, overlay, or by pressing the ESC key.

### Recommendations

#### Markup and JSX
- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Not all fonts have alternatives
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
    * Next router is used
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [x]  The code is clean and easy to understand:
  - The code is readable and structured clearly. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, a variable is declared but not used, or there is some kind of redundant logic.
  - The code is formatted in the same way, the indentation hierarchy is respected.

## Number of points: 67

**Comment by RandyPol** [comment]
I made improvements to the application by implementing error handling for signing in and signing out, as well as different API calls to fetch prompt data for both the Feed component and the profile.

Furthermore, I enhanced the user experience by removing the infinite loading spinner from the profile and feed components. Now, when a user signs out while on the profile page, they are presented with a message prompting them to sign in, replacing the previous spinning effect.

**Comment by FiLLa-FaS** [comment]
Hey! Thank you for the response, I hope you've learned about new features during this stage. I'm happy to say that your project is accepted, because you've got more than 80 points! Good luck on the next stage 🙌

# Summary:
### Performance Criteria

#### Markup and JSX
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the `overflow: hidden` declaration.
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Nav menu is not displayed on 320 viewport, so I can't get the access to another pages on 320 viewport, I can't logout or create a new prompt because there's no elements for that
- [x]  Elements specified in the UI toolkit are used correctly (e.g. buttons, forms, text elements, etc).
- [ ]  Classes are named according to BEM specifications.
    * BEM is not applied correctly on the page - you use only blocks and modifiers entities without any connection between. Even with new technologies you still need correct final BEM class naming for better methodology scaling and supporting even big projects
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [ ] A `fonts` folder.
      * You should add fonts locally and import them using `@font-face` css rule
- [x]  There are no linting errors or warnings.

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`
- [x]  No third-party JavaScript libraries are used unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [x]  API requests are described inside the `App` component.
- [x]  There is no memory leak when hanging handlers. All handlers added with addEventListener are removed when the component is unmounted.
- [x]  API error handling:
  - [x] The user receives a message in case of an error.
- [x]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
- [x]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed by clicking on the cross button, overlay, or by pressing the ESC key.

### Recommendations

#### Markup and JSX
- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Not all fonts have alternatives
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [x]  The code is clean and easy to understand:
  - The code is readable and structured clearly. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, a variable is declared but not used, or there is some kind of redundant logic.
  - The code is formatted in the same way, the indentation hierarchy is respected.

## Number of points: 85

**Comment by RandyPol** [comment]
@FiLLa-FaS Thank you for your guidance.

**Pull request merged**
